import { expect, test } from '@playwright/test';
import { waitForStoryRendered } from './story-ready';

/**
 * Visual regression tests for @rtkelly/design-system.
 *
 * These tests run on Linux (CI environment) because Playwright screenshots
 * are platform-specific due to OS font rendering differences.
 *
 * To update snapshots:
 * 1. Run: pnpm test:visual:update
 * 2. Or trigger GitHub Actions workflow with update_snapshots enabled.
 */

// Skip visual tests on non-Linux platforms (local dev on macOS/Windows)
test.skip(process.platform !== 'linux', 'Visual tests run on Linux CI');

/**
 * A fixed delay used to be the only wait here, which is how every baseline in
 * this suite came to be a screenshot of Storybook's "No Preview" panel: the
 * page had painted, so the shot succeeded, but no story had rendered.
 */
async function waitForStoryReady(page: import('@playwright/test').Page, storyId: string) {
  await waitForStoryRendered(page, storyId);
  await page.waitForTimeout(300);
}

interface VisualCase {
  /** Storybook story id, as it appears in `index.json`. */
  id: string;
  /** Baseline filename. Stable — renaming one orphans its committed PNG. */
  snapshot: string;
  fullPage?: boolean;
}

/**
 * The suite is a table rather than a test per story so that adding a component
 * means adding a row. It covered five stories while being a required check,
 * which made "visual regression passed" mean very little.
 *
 * One representative story per component, not every story: each row is a
 * committed PNG that a human has to review whenever it changes, so breadth
 * across components is worth more than depth within one.
 *
 * The first five names are unchanged from when this file listed them by hand —
 * their baselines are still valid and must not be regenerated by a rename.
 */
const CASES: readonly VisualCase[] = [
  { id: 'foundations-button--default', snapshot: 'button-default.png' },
  { id: 'foundations-button--bracketed', snapshot: 'button-bracketed.png' },
  { id: 'foundations-card--default', snapshot: 'card-default.png' },
  { id: 'presentation-slidedeck--default-deck', snapshot: 'slidedeck-default.png' },
  { id: 'blog-loremipsumpost--foundational-blog-post', snapshot: 'blog-post-foundational.png', fullPage: true },

  { id: 'foundations-badge--emphasis', snapshot: 'badge-emphasis.png' },
  { id: 'foundations-swatch--group', snapshot: 'swatch-group.png' },
  { id: 'foundations-badge--intent', snapshot: 'badge-intent.png' },
  { id: 'foundations-tag--row', snapshot: 'tag-row.png' },
  { id: 'foundations-brackettext--emphasis', snapshot: 'brackettext-emphasis.png' },
  { id: 'foundations-divider--patterns', snapshot: 'divider-patterns.png' },
  { id: 'foundations-pagetitle--with-subtitle', snapshot: 'pagetitle-with-subtitle.png' },
  { id: 'foundations-pageheader--with-children', snapshot: 'pageheader-with-children.png' },
  { id: 'foundations-noteblock--all-types', snapshot: 'noteblock-all-types.png' },
  { id: 'foundations-tldr--default', snapshot: 'tldr-default.png' },
  { id: 'foundations-modal--with-footer', snapshot: 'modal-with-footer.png' },
  { id: 'foundations-pagination--middle-page', snapshot: 'pagination-middle-page.png' },
  { id: 'foundations-sectioncontainer--default', snapshot: 'sectioncontainer-default.png' },

  { id: 'docs-breadcrumbs--default', snapshot: 'breadcrumbs-default.png' },
  { id: 'docs-codeblock--with-title-and-language', snapshot: 'codeblock-with-title-and-language.png' },
  { id: 'docs-codetabs--merged', snapshot: 'codetabs-merged.png' },
  { id: 'docs-prose--default', snapshot: 'prose-default.png', fullPage: true },
  { id: 'docs-anchorheading--levels', snapshot: 'anchorheading-levels.png' },
  { id: 'docs-tableofcontents--default', snapshot: 'tableofcontents-default.png' },
  { id: 'docs-docpager--both', snapshot: 'docpager-both.png' },
  { id: 'docs-docsheader--with-search', snapshot: 'docsheader-with-search.png' },
  { id: 'docs-docssidebar--default', snapshot: 'docssidebar-default.png' },

  { id: 'blog-blogpost--full-metadata', snapshot: 'blogpost-full-metadata.png', fullPage: true },
  { id: 'presentation-slide--with-subtitle', snapshot: 'slide-with-subtitle.png' },
  { id: 'showcase-experimentsview--default', snapshot: 'experimentsview-default.png', fullPage: true },

  // The remaining components, so that every component in the index has a
  // representative here and `check:visual-coverage` can demand that as the rule
  // rather than budgeting the gap.
  { id: 'foundations-avatar--default', snapshot: 'avatar-default.png' },
  { id: 'foundations-input--default-input', snapshot: 'input-default.png' },
  { id: 'foundations-statcard--system-health', snapshot: 'statcard-system-health.png' },
  { id: 'foundations-datatable--virtualized', snapshot: 'datatable-virtualized.png' },
  { id: 'foundations-semantic-tokens--roles', snapshot: 'semantic-tokens-roles.png', fullPage: true },
  { id: 'docs-docslayout--default', snapshot: 'docslayout-default.png', fullPage: true },
  { id: 'docs-portal--full-portal', snapshot: 'portal-full.png', fullPage: true },

  // The one case where a single screenshot is worth more than the others put
  // together: all four rungs side by side. The gated suite otherwise asserts one
  // level, so a token change that reads well on `midnight` and is unusable on
  // `white` passes everything. This is AGENTS.md rule 7's worked example and the
  // gap its own § *Screenshot Walkthrough* calls out.
  { id: 'foundations-theme-ladder--all-levels', snapshot: 'theme-ladder-all-levels.png', fullPage: true },

  // The two page-level shells, on both levels now that there are two rather
  // than four. `DimMode` is gone: with `dim` collapsed into `midnight` it
  // rendered exactly what `DarkMode` renders, so asserting both was asserting
  // the same pixels twice under two names.
  { id: 'saas-admindashboardlayout--dark-mode', snapshot: 'admin-dashboard-midnight.png', fullPage: true },
  { id: 'saas-admindashboardlayout--sketch-mode', snapshot: 'admin-dashboard-sketch.png', fullPage: true },
  { id: 'saas-landingpage--dark-mode', snapshot: 'saas-landing-midnight.png', fullPage: true },
  { id: 'saas-landingpage--sketch-mode', snapshot: 'saas-landing-sketch.png', fullPage: true },
];

/**
 * Interaction states, which the table above never reaches.
 *
 * Every case above renders a component **at rest**, and the aesthetic this
 * package exists for is an interaction one. `Button`'s `PRESS` constant declares
 * three states in one string and is shared across every accent *specifically* so
 * they cannot drift apart — a guarantee with nothing behind it while only the
 * resting state is captured.
 *
 * The focus row is the one that closes a known hole. `src/focus-ring.test.ts`
 * scans source for `outline-none` and says plainly why it is not the assertion
 * this deserves:
 *
 *   > Reading the resolved outline off a keyboard-focused control is the
 *   > assertion this deserves, and it is not available here: the cascade that
 *   > decides it lives in the Tailwind output generated at build time, which
 *   > jsdom never loads.
 *
 * Playwright does load it. `focus-visible` needs a *keyboard* focus rather than
 * `.focus()`, which is why these press `Tab` instead of calling it — a
 * programmatic focus does not match `:focus-visible` and would bake a ring-less
 * baseline while appearing to test the ring.
 *
 * Deliberately few. Each is a committed PNG a human reviews on every change, so
 * this covers the two states the system's identity rests on and the one that is
 * an accessibility guarantee — not every state of every component.
 */
interface InteractionCase extends VisualCase {
  /** What to do before capturing. `target` is resolved inside the story frame. */
  act: 'hover' | 'keyboard-focus' | 'press';
  /** CSS selector for the control to drive. */
  target: string;
}

const INTERACTIONS: readonly InteractionCase[] = [
  {
    id: 'foundations-button--default',
    snapshot: 'button-hover.png',
    act: 'hover',
    target: '#storybook-root button',
  },
  {
    id: 'foundations-button--default',
    snapshot: 'button-pressed.png',
    act: 'press',
    target: '#storybook-root button',
  },
  {
    id: 'foundations-input--default-input',
    snapshot: 'input-keyboard-focus.png',
    act: 'keyboard-focus',
    target: '#storybook-root input',
  },
];

/**
 * The narrow viewport, where behaviour exists that the desktop set cannot reach.
 *
 * Every other case in this file is Desktop Chrome at 1280x720, so the docs
 * sidebar toggle, its scrim, the admin drawer and the responsive type and
 * padding steps were asserted nowhere. `walkthrough` captures them, and
 * `AGENTS.md` says plainly that it is not a gate and its report is "nobody's job
 * to look" at.
 *
 * Deliberately five, not forty-one. Each is a committed PNG a human reviews on
 * every change, and the point is the layout that *differs* at this width — a
 * second copy of a component that renders identically is cost without evidence.
 *
 * The `-mobile` filenames are load-bearing: `snapshotPathTemplate` carries no
 * `{projectName}`, so both projects resolve to the same path. Naming them here
 * avoided renaming 44 existing baselines to add a segment.
 */
const MOBILE_CASES: readonly VisualCase[] = [
  { id: 'docs-docslayout--mobile-drawer', snapshot: 'docs-layout-mobile.png', fullPage: true },
  { id: 'saas-admindashboardlayout--dark-mode', snapshot: 'admin-dashboard-mobile.png', fullPage: true },
  { id: 'saas-landingpage--dark-mode', snapshot: 'saas-landing-mobile.png', fullPage: true },
  { id: 'foundations-pageheader--default', snapshot: 'pageheader-mobile.png' },
  { id: 'foundations-card--default', snapshot: 'card-mobile.png' },
];

test.describe('Design System Visual Regression - Narrow viewport', () => {
  for (const { id, snapshot, fullPage } of MOBILE_CASES) {
    test(`${id} — mobile`, async ({ page }, testInfo) => {
      test.skip(testInfo.project.name !== 'mobile', 'Narrow-viewport cases run in the mobile project');
      await page.goto(`/iframe.html?id=${id}&viewMode=story`);
      await waitForStoryReady(page, id);
      await expect(page).toHaveScreenshot(snapshot, fullPage ? { fullPage: true } : undefined);
    });
  }
});

test.describe('Design System Visual Regression - Interaction states', () => {
  for (const { id, snapshot, act, target } of INTERACTIONS) {
    test(`${id} — ${act}`, async ({ page }, testInfo) => {
      test.skip(testInfo.project.name !== 'chromium', 'Interaction baselines are the chromium project');
      await page.goto(`/iframe.html?id=${id}&viewMode=story`);
      await waitForStoryReady(page, id);

      /*
       * Suppress transitions before driving anything. `Button` carries
       * `transition-all duration-200`, so a press captured immediately after
       * `mouse.down()` lands *mid-interpolation* — measured at rest-to-pressed
       * 23% of the way through, with a 0.93px shadow offset that is a different
       * number on every run. That is exactly the race
       * `docs/deterministic-rendering.md` tells consumers to suppress, and this
       * suite is one of the consumers it is written for.
       *
       * Scoped to `#storybook-root` for a related reason: the iframe carries
       * four `button` elements, and the first in document order is Storybook's
       * own chrome, which has no bounding box and cannot be hovered.
       */
      await page.addStyleTag({
        content: '*,*::before,*::after{transition:none!important;animation:none!important}',
      });
      const el = page.locator(target).first();

      if (act === 'hover') {
        await el.hover();
      } else if (act === 'keyboard-focus') {
        // Tab, not `.focus()` — `:focus-visible` does not match a programmatic
        // focus, so calling it would capture a ring-less baseline and look like
        // a passing test of the ring.
        await page.keyboard.press('Tab');
        await expect(el).toBeFocused();
      } else {
        await el.hover();
        await page.mouse.down();
      }

      await expect(page).toHaveScreenshot(snapshot);
      if (act === 'press') await page.mouse.up();
    });
  }
});

test.describe('Design System Visual Regression - Components', () => {
  for (const { id, snapshot, fullPage } of CASES) {
    test(`${id}`, async ({ page }, testInfo) => {
      test.skip(testInfo.project.name !== 'chromium', 'Desktop baselines are the chromium project');
      await page.goto(`/iframe.html?id=${id}&viewMode=story`);
      await waitForStoryReady(page, id);
      await expect(page).toHaveScreenshot(snapshot, fullPage ? { fullPage: true } : undefined);
    });
  }
});
