import { expect, test } from '@playwright/test';
import { waitForStoryRendered } from './story-ready';

/**
 * Visual regression tests for @rtkelly/design-system.
 *
 * These tests run on Linux (CI environment) because Playwright screenshots
 * are platform-specific due to OS font rendering differences.
 *
 * To update snapshots:
 * 1. Run: pnpm test:visual:update
 * 2. Or trigger GitHub Actions workflow with update_snapshots enabled.
 */

// Skip visual tests on non-Linux platforms (local dev on macOS/Windows)
test.skip(process.platform !== 'linux', 'Visual tests run on Linux CI');

/**
 * A fixed delay used to be the only wait here, which is how every baseline in
 * this suite came to be a screenshot of Storybook's "No Preview" panel: the
 * page had painted, so the shot succeeded, but no story had rendered.
 */
async function waitForStoryReady(page: import('@playwright/test').Page, storyId: string) {
  await waitForStoryRendered(page, storyId);
  await page.waitForTimeout(300);
}

interface VisualCase {
  /** Storybook story id, as it appears in `index.json`. */
  id: string;
  /** Baseline filename. Stable — renaming one orphans its committed PNG. */
  snapshot: string;
  fullPage?: boolean;
  /**
   * A selector that must lie wholly inside the viewport before the capture —
   * for the floating elements, whose failure mode is rendering off-screen.
   * A screenshot of a clipped popup is still a screenshot, so the bounds are
   * asserted as numbers rather than left for a reviewer to notice.
   */
  onScreen?: string;
}

/**
 * The suite is a table rather than a test per story so that adding a component
 * means adding a row. It covered five stories while being a required check,
 * which made "visual regression passed" mean very little.
 *
 * One representative story per component, not every story: each row is a
 * committed PNG that a human has to review whenever it changes, so breadth
 * across components is worth more than depth within one.
 *
 * The first five names are unchanged from when this file listed them by hand —
 * their baselines are still valid and must not be regenerated by a rename.
 */
const CASES: readonly VisualCase[] = [
  { id: 'foundations-button--default', snapshot: 'button-default.png' },
  { id: 'foundations-button--bracketed', snapshot: 'button-bracketed.png' },
  { id: 'foundations-card--default', snapshot: 'card-default.png' },
  { id: 'presentation-slidedeck--default-deck', snapshot: 'slidedeck-default.png' },
  { id: 'blog-loremipsumpost--foundational-blog-post', snapshot: 'blog-post-foundational.png', fullPage: true },

  { id: 'foundations-badge--emphasis', snapshot: 'badge-emphasis.png' },
  { id: 'foundations-swatch--group', snapshot: 'swatch-group.png' },
  { id: 'foundations-badge--intent', snapshot: 'badge-intent.png' },
  { id: 'foundations-tag--row', snapshot: 'tag-row.png' },
  { id: 'foundations-brackettext--emphasis', snapshot: 'brackettext-emphasis.png' },
  { id: 'foundations-divider--patterns', snapshot: 'divider-patterns.png' },
  { id: 'foundations-pagetitle--with-subtitle', snapshot: 'pagetitle-with-subtitle.png' },
  { id: 'foundations-pageheader--with-children', snapshot: 'pageheader-with-children.png' },
  { id: 'foundations-noteblock--all-types', snapshot: 'noteblock-all-types.png' },
  { id: 'foundations-tldr--default', snapshot: 'tldr-default.png' },
  { id: 'foundations-modal--with-footer', snapshot: 'modal-with-footer.png' },
  { id: 'foundations-alertdialog--destructive', snapshot: 'alertdialog-destructive.png' },
  { id: 'foundations-drawer--from-the-right', snapshot: 'drawer-from-the-right.png' },
  { id: 'foundations-toast--all-intents', snapshot: 'toast-all-intents.png' },
  // The application shell (issue 247), asked to open its sidebar and at a
  // width where it must not: the persistent column, no drawer. The same story
  // is in `MOBILE_CASES` below with the drawer open, so the pair asserts the
  // desktop and off-canvas layouts as one component.
  { id: 'foundations-appshell--sidebar-open', snapshot: 'appshell-sidebar-open.png' },
  // The floating set (#166), each open on load: a tooltip, popover or menu
  // asserted closed asserts nothing — the trap #132 names for press states.
  { id: 'foundations-tooltip--on-an-icon-button', snapshot: 'tooltip-on-an-icon-button.png' },
  { id: 'foundations-popover--open', snapshot: 'popover-open.png' },
  { id: 'foundations-menu--actions', snapshot: 'menu-actions.png' },
  // `fullPage`: the report frame is a page, and the part most likely to drift
  // — the header strip against the body rhythm — is only visible whole.
  {
    id: 'foundations-reportdocument--quality-gate',
    snapshot: 'reportdocument-quality-gate.png',
    fullPage: true,
  },
  { id: 'foundations-pagination--middle-page', snapshot: 'pagination-middle-page.png' },
  // The ellipsis form, which `MiddlePage`'s five pages never reach: first,
  // last, a window around current and both gaps, at the fixed seven slots.
  // In navigation mode deliberately — `MiddlePage` is callback mode, so the
  // two rows put both of Pagination's element trees in front of axe as well.
  { id: 'foundations-pagination--as-links-many-pages', snapshot: 'pagination-as-links-many-pages.png' },
  // The general tab set, not the code one: `docs-codetabs--merged` below asserts
  // the same tablist wearing `CodeTabs`, and the pair is what shows the
  // extraction rendering identically in both places.
  { id: 'foundations-tabs--default', snapshot: 'tabs-default.png' },
  // The site chrome (issue 246), on the four sites the issue says the same
  // four components must build unmodified: each is a whole page — header,
  // main, footer — so a prop that one site needed and another broke shows up
  // here. The desktop row; the narrow-viewport half is in MOBILE_CASES.
  { id: 'foundations-siteheader--portfolio', snapshot: 'siteheader-portfolio.png' },
  { id: 'foundations-siteheader--blog', snapshot: 'siteheader-blog.png' },
  { id: 'foundations-siteheader--marketing', snapshot: 'siteheader-marketing.png' },
  { id: 'foundations-siteheader--project-site', snapshot: 'siteheader-project-site.png' },
  // A group open on load: the `Menu` its links open in, anchored to the nav.
  { id: 'foundations-sitenav--with-children', snapshot: 'sitenav-with-children.png' },
  { id: 'foundations-sitefooter--columns', snapshot: 'sitefooter-columns.png' },
  // The marketing sections (issue 248), one row per section, each a layout
  // holding only the fixture copy its story passes it.
  { id: 'foundations-hero--default', snapshot: 'hero-default.png' },
  { id: 'foundations-featuregrid--default', snapshot: 'featuregrid-default.png', fullPage: true },
  { id: 'foundations-pricinggrid--default', snapshot: 'pricinggrid-default.png', fullPage: true },
  { id: 'foundations-ctasection--default', snapshot: 'ctasection-default.png' },
  { id: 'foundations-sectioncontainer--default', snapshot: 'sectioncontainer-default.png' },

  { id: 'docs-breadcrumbs--default', snapshot: 'breadcrumbs-default.png' },
  { id: 'docs-codeblock--with-title-and-language', snapshot: 'codeblock-with-title-and-language.png' },
  { id: 'docs-codetabs--merged', snapshot: 'codetabs-merged.png' },
  { id: 'docs-prose--default', snapshot: 'prose-default.png', fullPage: true },
  { id: 'docs-anchorheading--levels', snapshot: 'anchorheading-levels.png' },
  { id: 'docs-tableofcontents--default', snapshot: 'tableofcontents-default.png' },
  { id: 'docs-docpager--both', snapshot: 'docpager-both.png' },
  { id: 'docs-docsheader--with-search', snapshot: 'docsheader-with-search.png' },
  { id: 'docs-docssidebar--default', snapshot: 'docssidebar-default.png' },

  { id: 'blog-blogpost--full-metadata', snapshot: 'blogpost-full-metadata.png', fullPage: true },
  // The author card as data and as a slot (issue 250): a guest's derived
  // initials, link and bio; an `Avatar` in the initials' place; and the
  // `authorCard` slot replacing the card. The default card is the row above.
  { id: 'blog-blogpost--guest-author', snapshot: 'blogpost-guest-author.png', fullPage: true },
  { id: 'blog-blogpost--with-avatar', snapshot: 'blogpost-with-avatar.png', fullPage: true },
  { id: 'blog-blogpost--custom-author-card', snapshot: 'blogpost-custom-author-card.png', fullPage: true },
  { id: 'presentation-slide--with-subtitle', snapshot: 'slide-with-subtitle.png' },
  { id: 'showcase-experimentsview--default', snapshot: 'experimentsview-default.png', fullPage: true },

  // The remaining components, so that every component in the index has a
  // representative here and `check:visual-coverage` can demand that as the rule
  // rather than budgeting the gap.
  { id: 'foundations-avatar--default', snapshot: 'avatar-default.png' },
  { id: 'foundations-input--default-input', snapshot: 'input-default.png' },
  // The booleans, one row each and both on their `AllStates` story: box,
  // mark, track, thumb travel, disabled treatment and error border in a
  // single reviewed PNG rather than eight almost-identical ones.
  { id: 'foundations-checkbox--all-states', snapshot: 'checkbox-all-states.png' },
  { id: 'foundations-switch--all-states', snapshot: 'switch-all-states.png' },
  // The groups (#239), on their `AllStates` stories for the same reason: the
  // legend, the group message, the invalid border and group- and option-level
  // disabled in one reviewed PNG each. `Fieldset`'s row is a checkbox set and
  // an input pair, so the frame is asserted around something other than radios.
  { id: 'foundations-radiogroup--all-states', snapshot: 'radiogroup-all-states.png' },
  // `Select` at rest (#164): chosen, placeholder, invalid, disabled, native
  // and a second accent. The open list is an interaction row below, since a
  // list that is open on mount would steal focus on the docs page.
  { id: 'foundations-select--all-states', snapshot: 'select-all-states.png' },
  { id: 'foundations-fieldset--all-states', snapshot: 'fieldset-all-states.png' },
  // The form layer's proof (issue 50): one account-settings form holding every
  // control, a disabled one, required ones, helper text and field errors, in
  // the state after a failed save — so `ErrorSummary` is asserted with focus
  // on it and five links, and the a11y suite axes the error state, which is
  // the one that fails. `fullPage`: the form runs past the fold.
  {
    id: 'foundations-errorsummary--account-settings',
    snapshot: 'errorsummary-account-settings.png',
    fullPage: true,
  },
  { id: 'foundations-statcard--system-health', snapshot: 'statcard-system-health.png' },
  { id: 'foundations-datatable--virtualized', snapshot: 'datatable-virtualized.png' },
  // The semantics at rest (#245): a caption, a row-header column in the body
  // cell's geometry, and a sorted column's icon. Also the a11y suite's sorted,
  // non-virtualized case, since that suite reads its story list from here.
  { id: 'foundations-datatable--sorted-with-caption', snapshot: 'datatable-sorted-with-caption.png' },
  // The pager under a paginated body (issue 276): the table and `Pagination` together.
  { id: 'foundations-datatable--paginated', snapshot: 'datatable-paginated.png' },
  { id: 'foundations-semantic-tokens--roles', snapshot: 'semantic-tokens-roles.png', fullPage: true },
  { id: 'docs-docslayout--default', snapshot: 'docslayout-default.png', fullPage: true },
  { id: 'docs-portal--full-portal', snapshot: 'portal-full.png', fullPage: true },

  // The one case where a single screenshot is worth more than the others put
  // together: all four rungs side by side. The gated suite otherwise asserts one
  // level, so a token change that reads well on `midnight` and is unusable on
  // `white` passes everything. This is AGENTS.md rule 7's worked example and the
  // gap its own § *Screenshot Walkthrough* calls out.
  { id: 'foundations-theme-ladder--all-levels', snapshot: 'theme-ladder-all-levels.png', fullPage: true },

  // The two page-level shells, on both levels now that there are two rather
  // than four. `DimMode` is gone: with `dim` collapsed into `midnight` it
  // rendered exactly what `DarkMode` renders, so asserting both was asserting
  // the same pixels twice under two names.
  { id: 'saas-admindashboardlayout--dark-mode', snapshot: 'admin-dashboard-midnight.png', fullPage: true },
  { id: 'saas-admindashboardlayout--sketch-mode', snapshot: 'admin-dashboard-sketch.png', fullPage: true },
  { id: 'saas-landingpage--dark-mode', snapshot: 'saas-landing-midnight.png', fullPage: true },
  { id: 'saas-landingpage--sketch-mode', snapshot: 'saas-landing-sketch.png', fullPage: true },
  // Two more landing pages from the same sections as `SaasLandingPage` (issue
  // 248): a different order and a different set, one with pricing and one
  // without. Neither pins a Level, so the a11y suite axes both on both.
  { id: 'saas-landingpage--product-launch', snapshot: 'saas-landing-product-launch.png', fullPage: true },
  { id: 'saas-landingpage--project-site', snapshot: 'saas-landing-project-site.png', fullPage: true },

  // Chart Primitives
  { id: 'foundations-barchart--vertical', snapshot: 'barchart-vertical.png' },
  { id: 'foundations-sparkline--primary-trend', snapshot: 'sparkline-primary-trend.png' },
  { id: 'foundations-bulletchart--primary-benchmark', snapshot: 'bulletchart-primary-benchmark.png' },
  { id: 'foundations-charttooltip--primary', snapshot: 'charttooltip-primary.png' },
  { id: 'foundations-socialicon--brand-marks', snapshot: 'socialicon-brand-marks.png' },

  // System feedback. Each row is the state that rots unseen — a loading card
  // nobody looks at until the network is slow, an empty table nobody looks at
  // until the filter matches nothing.
  //
  // The two animated ones are captured at rest by construction:
  // `animations: 'disabled'` resets an infinite animation to its first frame,
  // so `Spinner`'s mark and the indeterminate sweep are the same pixels every
  // run. The representative chosen for each is therefore the one with the most
  // structure rather than the one that moves least.
  { id: 'foundations-spinner--sizes', snapshot: 'spinner-sizes.png' },
  { id: 'foundations-skeleton--loading-card', snapshot: 'skeleton-loading-card.png' },
  { id: 'foundations-progress--accents', snapshot: 'progress-accents.png' },
  { id: 'foundations-emptystate--first-run', snapshot: 'emptystate-first-run.png' },
  // mdxcn-derived docs diagrams. Each component is asserted on both the
  // default midnight level and its explicit sketch story so a token change
  // cannot be healthy in one palette while broken in the other.
  { id: 'docs-graphframe--default', snapshot: 'graphframe-default.png' },
  { id: 'docs-graphframe--sketch-theme', snapshot: 'graphframe-sketch.png' },
  { id: 'docs-graphflow--default', snapshot: 'graphflow-default.png' },
  { id: 'docs-graphflow--sketch-theme', snapshot: 'graphflow-sketch.png' },
  { id: 'docs-graphtimeline--default', snapshot: 'graphtimeline-default.png' },
  { id: 'docs-graphtimeline--sketch-theme', snapshot: 'graphtimeline-sketch.png' },
  { id: 'docs-graphdiff--default', snapshot: 'graphdiff-default.png' },
  { id: 'docs-graphdiff--sketch-theme', snapshot: 'graphdiff-sketch.png' },
  { id: 'docs-graphslope--default', snapshot: 'graphslope-default.png' },
  { id: 'docs-graphslope--sketch-theme', snapshot: 'graphslope-sketch.png' },
  { id: 'docs-graphuptime--default', snapshot: 'graphuptime-default.png' },
  { id: 'docs-graphuptime--sketch-theme', snapshot: 'graphuptime-sketch.png' },
  { id: 'docs-graphtree--default', snapshot: 'graphtree-default.png' },
  { id: 'docs-graphtree--sketch-theme', snapshot: 'graphtree-sketch.png' },
  { id: 'docs-terminal--default', snapshot: 'terminal-default.png' },
  { id: 'docs-terminal--sketch-theme', snapshot: 'terminal-sketch.png' },
  { id: 'docs-steps--default', snapshot: 'steps-default.png' },
  { id: 'docs-steps--sketch-theme', snapshot: 'steps-sketch.png' },
];

/**
 * Interaction states, which the table above never reaches.
 *
 * Every case above renders a component **at rest**, and the aesthetic this
 * package exists for is an interaction one. `Button`'s `PRESS` constant declares
 * three states in one string and is shared across every accent *specifically* so
 * they cannot drift apart — a guarantee with nothing behind it while only the
 * resting state is captured.
 *
 * The focus row is the one that closes a known hole. `src/focus-ring.test.ts`
 * scans source for `outline-none` and says plainly why it is not the assertion
 * this deserves:
 *
 *   > Reading the resolved outline off a keyboard-focused control is the
 *   > assertion this deserves, and it is not available here: the cascade that
 *   > decides it lives in the Tailwind output generated at build time, which
 *   > jsdom never loads.
 *
 * Playwright does load it. `focus-visible` needs a *keyboard* focus rather than
 * `.focus()`, which is why these press `Tab` instead of calling it — a
 * programmatic focus does not match `:focus-visible` and would bake a ring-less
 * baseline while appearing to test the ring.
 *
 * Deliberately few. Each is a committed PNG a human reviews on every change, so
 * this covers the two states the system's identity rests on and the one that is
 * an accessibility guarantee — not every state of every component.
 */
interface InteractionCase extends VisualCase {
  /**
   * What to do before capturing. `target` is resolved inside the story frame.
   * `open` focuses the target and presses ArrowDown, then `keys` — the
   * keyboard path, so what is highlighted does not depend on where the
   * pointer happens to rest.
   */
  act: 'hover' | 'keyboard-focus' | 'press' | 'open';
  /** CSS selector for the control to drive. */
  target: string;
  /** Pressed after an `open`, inside the list. */
  keys?: readonly string[];
  /**
   * The Level to render on, for a surface whose whole point is that it is
   * painted by the Level. Omitted, the story's default (`midnight`).
   */
  level?: 'sketch';
}

const INTERACTIONS: readonly InteractionCase[] = [
  {
    id: 'foundations-button--default',
    snapshot: 'button-hover.png',
    act: 'hover',
    target: '#storybook-root button',
  },
  {
    id: 'foundations-button--default',
    snapshot: 'button-pressed.png',
    act: 'press',
    target: '#storybook-root button',
  },
  {
    id: 'foundations-input--default-input',
    snapshot: 'input-keyboard-focus.png',
    act: 'keyboard-focus',
    target: '#storybook-root input',
  },
  // `Select`'s open list (#164), the surface the operating system used to
  // paint. Opened on the chosen row, then one ArrowDown, so a single frame
  // holds all four row states: the chosen row's mark, the highlighted fill
  // (the next row), the disabled row it stepped over, and plain rows. Both
  // Levels, because being drawn by the Level is the issue.
  {
    id: 'foundations-select--disabled-option',
    snapshot: 'select-open-midnight.png',
    act: 'open',
    target: '#storybook-root [role="combobox"]',
    keys: ['ArrowDown'],
  },
  {
    id: 'foundations-select--disabled-option',
    snapshot: 'select-open-sketch.png',
    act: 'open',
    target: '#storybook-root [role="combobox"]',
    keys: ['ArrowDown'],
    level: 'sketch',
  },
];

/**
 * The narrow viewport, where behaviour exists that the desktop set cannot reach.
 *
 * Every other case in this file is Desktop Chrome at 1280x720, so the docs
 * sidebar toggle, its scrim, the admin drawer and the responsive type and
 * padding steps were asserted nowhere. `walkthrough` captures them, and
 * `AGENTS.md` says plainly that it is not a gate and its report is "nobody's job
 * to look" at.
 *
 * Deliberately eighteen, not forty-one. Each is a committed PNG a human reviews on
 * every change, and the point is the layout that *differs* at this width — a
 * second copy of a component that renders identically is cost without evidence.
 * `Drawer` is the sixth and the clearest case for the rule: it is the one
 * component in the package whose reason for existing is this viewport.
 *
 * The `-mobile` filenames are load-bearing: `snapshotPathTemplate` carries no
 * `{projectName}`, so both projects resolve to the same path. Naming them here
 * avoided renaming 44 existing baselines to add a segment.
 */
const MOBILE_CASES: readonly VisualCase[] = [
  { id: 'docs-docslayout--mobile-drawer', snapshot: 'docs-layout-mobile.png', fullPage: true },
  { id: 'saas-admindashboardlayout--dark-mode', snapshot: 'admin-dashboard-mobile.png', fullPage: true },
  { id: 'saas-landingpage--dark-mode', snapshot: 'saas-landing-mobile.png', fullPage: true },
  { id: 'foundations-pageheader--default', snapshot: 'pageheader-mobile.png' },
  { id: 'foundations-card--default', snapshot: 'card-mobile.png' },
  // The drawer, at the width it exists for. The desktop row above captures a
  // 384px panel against 1280px of backdrop; at 412px it is most of the screen,
  // which is the layout a mobile nav actually ships as. Asserting only the
  // desktop one would assert the case nobody meets.
  { id: 'foundations-drawer--from-the-left', snapshot: 'drawer-from-the-left-mobile.png' },
  // The application shell's other layout (issue 247). Collapsed: no sidebar
  // column, the toggle at the head of the topbar. Open: the desktop row's
  // story again, where the same request now puts the sidebar in a left
  // drawer — `onScreen` asserts the panel is actually in the viewport.
  { id: 'foundations-appshell--default', snapshot: 'appshell-default-mobile.png' },
  {
    id: 'foundations-appshell--sidebar-open',
    snapshot: 'appshell-sidebar-open-mobile.png',
    onScreen: '[data-slot="drawer"]',
  },
  // Pagination's degraded form. At this width the seven-slot page list gives
  // way to the `[ 7 / 20 ]` status instead of wrapping onto a second line —
  // behaviour that exists only below `md`, so asserting it anywhere else
  // would be assuming it.
  { id: 'foundations-pagination--many-pages', snapshot: 'pagination-many-pages-mobile.png' },
  // Collision (#166). Each trigger sits hard against the right edge asking to
  // open rightward, which at 412px has no room: the positioning engine must
  // flip or shift it back on-screen, and `onScreen` asserts that it did rather
  // than trusting the library to.
  {
    id: 'foundations-tooltip--at-the-viewport-edge',
    snapshot: 'tooltip-at-the-viewport-edge-mobile.png',
    onScreen: '[data-slot="tooltip"]',
  },
  {
    id: 'foundations-popover--at-the-viewport-edge',
    snapshot: 'popover-at-the-viewport-edge-mobile.png',
    onScreen: '[data-slot="popover"]',
  },
  {
    id: 'foundations-menu--at-the-viewport-edge',
    snapshot: 'menu-at-the-viewport-edge-mobile.png',
    onScreen: '[data-slot="menu"]',
  },
  // The site chrome's breakpoint (issue 246), which is the whole point of
  // `MobileNav`: a desktop-only baseline asserts none of it. The marketing
  // header closed — the row gone, the `MENU` trigger in its place — and two
  // pages with the drawer open, one of them holding a group's `Menu` trigger.
  // The a11y suite reads these ids too, so the nav is axed open and closed.
  { id: 'foundations-siteheader--marketing', snapshot: 'siteheader-marketing-mobile.png' },
  {
    id: 'foundations-mobilenav--open',
    snapshot: 'mobilenav-open-mobile.png',
    onScreen: '[data-slot="drawer"]',
  },
  {
    id: 'foundations-mobilenav--with-group',
    snapshot: 'mobilenav-with-group-mobile.png',
    onScreen: '[data-slot="drawer"]',
  },
  // The account-settings proof (issue 50) at a phone's width: the profile row's
  // two columns stack, and the summary's links and the long field errors wrap —
  // a layout the desktop row never reaches.
  {
    id: 'foundations-errorsummary--account-settings',
    snapshot: 'errorsummary-account-settings-mobile.png',
    fullPage: true,
  },
  // The marketing sections' breakpoint (issue 248): every grid drops to one
  // column below `md` and the hero's actions wrap. Both composed pages, since
  // the point of the issue is that two different pages survive this width.
  { id: 'saas-landingpage--product-launch', snapshot: 'saas-landing-product-launch-mobile.png', fullPage: true },
  { id: 'saas-landingpage--project-site', snapshot: 'saas-landing-project-site-mobile.png', fullPage: true },
];

test.describe('Design System Visual Regression - Narrow viewport', () => {
  for (const { id, snapshot, fullPage, onScreen } of MOBILE_CASES) {
    test(`${id} — mobile`, async ({ page }, testInfo) => {
      test.skip(testInfo.project.name !== 'mobile', 'Narrow-viewport cases run in the mobile project');
      await page.goto(`/iframe.html?id=${id}&viewMode=story`);
      await waitForStoryReady(page, id);
      if (onScreen) {
        const box = await page.locator(onScreen).boundingBox();
        const viewport = page.viewportSize();
        expect(box, `${onScreen} rendered`).not.toBeNull();
        expect(viewport).not.toBeNull();
        if (box && viewport) {
          expect(box.x).toBeGreaterThanOrEqual(0);
          expect(box.y).toBeGreaterThanOrEqual(0);
          expect(box.x + box.width).toBeLessThanOrEqual(viewport.width);
          expect(box.y + box.height).toBeLessThanOrEqual(viewport.height);
        }
      }
      await expect(page).toHaveScreenshot(snapshot, fullPage ? { fullPage: true } : undefined);
    });
  }
});

test.describe('Design System Visual Regression - Interaction states', () => {
  for (const { id, snapshot, act, target, keys, level } of INTERACTIONS) {
    test(`${id} — ${act}${level ? ` — ${level}` : ''}`, async ({ page }, testInfo) => {
      test.skip(testInfo.project.name !== 'chromium', 'Interaction baselines are the chromium project');
      await page.goto(`/iframe.html?id=${id}&viewMode=story${level ? `&globals=level:${level}` : ''}`);
      await waitForStoryReady(page, id);

      /*
       * Suppress transitions before driving anything. `Button` carries
       * `transition-all duration-200`, so a press captured immediately after
       * `mouse.down()` lands *mid-interpolation* — measured at rest-to-pressed
       * 23% of the way through, with a 0.93px shadow offset that is a different
       * number on every run. That is exactly the race
       * `docs/deterministic-rendering.md` tells consumers to suppress, and this
       * suite is one of the consumers it is written for.
       *
       * Scoped to `#storybook-root` for a related reason: the iframe carries
       * four `button` elements, and the first in document order is Storybook's
       * own chrome, which has no bounding box and cannot be hovered.
       */
      await page.addStyleTag({
        content: '*,*::before,*::after{transition:none!important;animation:none!important}',
      });
      const el = page.locator(target).first();

      if (act === 'hover') {
        await el.hover();
      } else if (act === 'keyboard-focus') {
        // Tab, not `.focus()` — `:focus-visible` does not match a programmatic
        // focus, so calling it would capture a ring-less baseline and look like
        // a passing test of the ring.
        await page.keyboard.press('Tab');
        await expect(el).toBeFocused();
      } else if (act === 'open') {
        // `.focus()` rather than Tab: the trigger's own ring is not in this
        // frame (focus moves into the list), and Tab raced the story mounting
        // often enough locally to be the flake this suite cannot afford.
        await el.focus();
        await expect(el).toBeFocused();
        await page.keyboard.press('ArrowDown');
        await expect(page.getByRole('listbox')).toBeVisible();
        for (const key of keys ?? []) await page.keyboard.press(key);
      } else {
        await el.hover();
        await page.mouse.down();
      }

      await expect(page).toHaveScreenshot(snapshot);
      if (act === 'press') await page.mouse.up();
    });
  }
});

test.describe('Design System Visual Regression - Components', () => {
  for (const { id, snapshot, fullPage } of CASES) {
    test(`${id}`, async ({ page }, testInfo) => {
      test.skip(testInfo.project.name !== 'chromium', 'Desktop baselines are the chromium project');
      await page.goto(`/iframe.html?id=${id}&viewMode=story`);
      await waitForStoryReady(page, id);
      await expect(page).toHaveScreenshot(snapshot, fullPage ? { fullPage: true } : undefined);
    });
  }
});
