import { expect, test } from '@playwright/test';
import { waitForStoryRendered } from './story-ready';

/**
 * Visual regression tests for @rtkelly/design-system.
 *
 * These tests run on Linux (CI environment) because Playwright screenshots
 * are platform-specific due to OS font rendering differences.
 *
 * To update snapshots:
 * 1. Run: pnpm test:visual:update
 * 2. Or trigger GitHub Actions workflow with update_snapshots enabled.
 */

// Skip visual tests on non-Linux platforms (local dev on macOS/Windows)
test.skip(process.platform !== 'linux', 'Visual tests run on Linux CI');

/**
 * A fixed delay used to be the only wait here, which is how every baseline in
 * this suite came to be a screenshot of Storybook's "No Preview" panel: the
 * page had painted, so the shot succeeded, but no story had rendered.
 */
async function waitForStoryReady(page: import('@playwright/test').Page, storyId: string) {
  await waitForStoryRendered(page, storyId);
  await page.waitForTimeout(300);
}

interface VisualCase {
  /** Storybook story id, as it appears in `index.json`. */
  id: string;
  /** Baseline filename. Stable — renaming one orphans its committed PNG. */
  snapshot: string;
  fullPage?: boolean;
}

/**
 * The suite is a table rather than a test per story so that adding a component
 * means adding a row. It covered five stories while being a required check,
 * which made "visual regression passed" mean very little.
 *
 * One representative story per component, not every story: each row is a
 * committed PNG that a human has to review whenever it changes, so breadth
 * across components is worth more than depth within one.
 *
 * The first five names are unchanged from when this file listed them by hand —
 * their baselines are still valid and must not be regenerated by a rename.
 */
const CASES: readonly VisualCase[] = [
  { id: 'foundations-button--default', snapshot: 'button-default.png' },
  { id: 'foundations-button--bracketed', snapshot: 'button-bracketed.png' },
  { id: 'foundations-card--default', snapshot: 'card-default.png' },
  { id: 'presentation-slidedeck--default-deck', snapshot: 'slidedeck-default.png' },
  { id: 'blog-loremipsumpost--foundational-blog-post', snapshot: 'blog-post-foundational.png', fullPage: true },

  { id: 'foundations-badge--emphasis', snapshot: 'badge-emphasis.png' },
  { id: 'foundations-badge--intent', snapshot: 'badge-intent.png' },
  { id: 'foundations-tag--row', snapshot: 'tag-row.png' },
  { id: 'foundations-brackettext--emphasis', snapshot: 'brackettext-emphasis.png' },
  { id: 'foundations-divider--patterns', snapshot: 'divider-patterns.png' },
  { id: 'foundations-pagetitle--with-subtitle', snapshot: 'pagetitle-with-subtitle.png' },
  { id: 'foundations-pageheader--with-children', snapshot: 'pageheader-with-children.png' },
  { id: 'foundations-noteblock--all-types', snapshot: 'noteblock-all-types.png' },
  { id: 'foundations-tldr--default', snapshot: 'tldr-default.png' },
  { id: 'foundations-modal--with-footer', snapshot: 'modal-with-footer.png' },
  { id: 'foundations-datatable--with-rendered-cells', snapshot: 'datatable-with-rendered-cells.png' },
  { id: 'foundations-pagination--middle-page', snapshot: 'pagination-middle-page.png' },
  { id: 'foundations-sectioncontainer--default', snapshot: 'sectioncontainer-default.png' },

  { id: 'docs-breadcrumbs--default', snapshot: 'breadcrumbs-default.png' },
  { id: 'docs-codeblock--with-title-and-language', snapshot: 'codeblock-with-title-and-language.png' },
  { id: 'docs-prose--default', snapshot: 'prose-default.png', fullPage: true },
  { id: 'docs-anchorheading--levels', snapshot: 'anchorheading-levels.png' },
  { id: 'docs-tableofcontents--default', snapshot: 'tableofcontents-default.png' },
  { id: 'docs-docpager--both', snapshot: 'docpager-both.png' },
  { id: 'docs-docsheader--with-search', snapshot: 'docsheader-with-search.png' },
  { id: 'docs-docssidebar--default', snapshot: 'docssidebar-default.png' },

  { id: 'blog-blogpost--full-metadata', snapshot: 'blogpost-full-metadata.png', fullPage: true },
  { id: 'presentation-slide--with-subtitle', snapshot: 'slide-with-subtitle.png' },
  { id: 'showcase-experimentsview--default', snapshot: 'experimentsview-default.png', fullPage: true },

  // The remaining components, so that every component in the index has a
  // representative here and `check:visual-coverage` can demand that as the rule
  // rather than budgeting the gap.
  { id: 'foundations-avatar--default', snapshot: 'avatar-default.png' },
  { id: 'foundations-input--default-input', snapshot: 'input-default.png' },
  { id: 'foundations-statcard--system-health', snapshot: 'statcard-system-health.png' },
  { id: 'foundations-semantic-tokens--roles', snapshot: 'semantic-tokens-roles.png', fullPage: true },
  { id: 'docs-docslayout--default', snapshot: 'docslayout-default.png', fullPage: true },
  { id: 'docs-portal--full-portal', snapshot: 'portal-full.png', fullPage: true },

  // The one case where a single screenshot is worth more than the others put
  // together: all four rungs side by side. The gated suite otherwise asserts one
  // level, so a token change that reads well on `midnight` and is unusable on
  // `white` passes everything. This is AGENTS.md rule 7's worked example and the
  // gap its own § *Screenshot Walkthrough* calls out.
  { id: 'foundations-theme-ladder--all-levels', snapshot: 'theme-ladder-all-levels.png', fullPage: true },

  // The report frame. `@rtkelly13/ds-report` renders reports into it, and that
  // package depends on this one — so this story composes the frame itself rather
  // than importing the generator's sample, which would invert the dependency.
  // This package asserts how the frame looks; the generator asserts its pipeline.
  // Full page, because a report is one.
  { id: 'foundations-reportdocument--quality-gate', snapshot: 'reportdocument-quality-gate.png', fullPage: true },

  // The two page-level shells. Their baselines will churn when the remaining
  // token migration reaches them, which is the intended behaviour and not a
  // reason to leave them unasserted — `dim` because it is the rung these
  // surfaces are meant to be read at.
  { id: 'saas-admindashboardlayout--dim-mode', snapshot: 'admin-dashboard-dim.png', fullPage: true },
  { id: 'saas-landingpage--dim-mode', snapshot: 'saas-landing-dim.png', fullPage: true },
];

test.describe('Design System Visual Regression - Components', () => {
  for (const { id, snapshot, fullPage } of CASES) {
    test(`${id}`, async ({ page }) => {
      await page.goto(`/iframe.html?id=${id}&viewMode=story`);
      await waitForStoryReady(page, id);
      await expect(page).toHaveScreenshot(snapshot, fullPage ? { fullPage: true } : undefined);
    });
  }
});
